{{- if .Values.frontendConfig.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.frontendConfig.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.frontendConfig.redirectToHttps.enabled }}
  redirectToHttps:
    enabled: true
    responseCodeName: {{ .Values.frontendConfig.redirectToHttps.responseCodeName }}
  {{- end }}
  {{- if .Values.sslPolicy }}
  sslPolicy: {{ .Values.sslPolicy | quote }}
  {{- end }}
{{- end }}