{{- if .Values.serviceTailscale.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceTailscale.name | default (printf "%s-tailscale" (include "nginx-chart.fullname" .)) }}
  {{- with .Values.serviceTailscale.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    tailscale.com/expose: "true"
    {{- with .Values.serviceTailscale.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ExternalName
  externalName: {{ required "A valid externalName is required!" .Values.serviceTailscale.externalName }}
{{- end }}
