{{- if .Values.frontendConfig.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.frontendConfig.name }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: {{ .Values.frontendConfig.redirectToHttps.enabled }}
    responseCodeName: {{ .Values.frontendConfig.redirectToHttps.responseCodeName }}
{{- end }}